src/Testjob/TestjobBundle/Entity/User.php
<?php

namespace Testjob\TestjobBundle\Entity;

use Symfony\Component\Security\Core\User\UserInterface;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="app_user")
 * @ORM\HasLifecycleCallbacks
 */
class User implements UserInterface
{
    const ROLE_ADMINISTRATOR ='ROLE_ADMIN';
    const ROLE_USER = 'ROLE_USER';

    const REGISTRATION_AWAIT = false;
    const REGISTRATION_APPROVED = true;

    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $fio;

    /**
     * @ORM\Column(type="string", unique=true)
     */
    private $login;

    /**
     * @ORM\Column(type="string", unique=true)
     */
    protected $email;

    /**
     * @ORM\Column(type="string", length=64)
     */
    protected $password;

    /**
     * @ORM\Column(type="boolean", options={"default" : FALSE})
     */
    protected $confirmed;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $created;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $registred;

    /**
     * @ORM\Column(type="boolean", options={"default" : FALSE})
     */
    protected $banned;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    protected $birthday;

    /**
     * @ORM\ManyToMany(targetEntity="Roles", inversedBy="users_group")
     */
    private $roles;

    /**
     * @ORM\OneToMany(targetEntity="Image", mappedBy="author")
     */
    protected $gallery;

    private $plainPassword;

    public function getId()
    {
        return $this->id;
    }

    public function getLogin()
    {
        return $this->login;
    }

    public function setLogin($login)
    {
        $this->login = $login;
    }

    public function getFio()
    {
        return $this->fio;
    }

    public function setFio($fio)
    {
        $this->fio = $fio;
    }

    public function getPassword()
    {
        return $this->password;
    }

    public function setPassword($password)
    {
        $this->password = $password;
    }

    public function getEmail()
    {
        return $this->email;
    }

    public function setEmail($email)
    {
        $this->email = $email;
    }


    public function getConfirmed()
    {
        return $this->confirmed;
    }

    public function setConfirmed($confirmed)
    {
        $this->confirmed = $confirmed;
    }

    public function getRegistred()
    {
        return $this->registred;
    }

    public function setRegistred()
    {
        $this->registred = new \DateTime();
    }

    public function getCreated()
    {
        return $this->created;
    }

    public function setCreated($created)
    {
        $this->created = $created;
    }

    public function getBanned()
    {
        return $this->banned;
    }

    public function setBanned($banned)
    {
        $this->banned = $banned;
    }

    public function getPlainPassword()
    {
        return $this->plainPassword;
    }

    public function setPlainPassword($plainPassword)
    {
        $this->plainPassword = $plainPassword;

        $this->password = null;
    }

    public function setBirthday($birthday)
    {
        $this->birthday = $birthday;
    }

    public function getBirthday()
    {
        return $this->birthday;
    }

    public function getGallery()
    {
        return $this->gallery;
    }

    public function setGallery(Image $image)
    {
        $this->gallery[] = $image;

        return $this;
    }

    public function getUsername()
    {
        return $this->login;
    }

    public function getSalt()
    {
        // TODO: Implement getSalt() method.
    }

    public function eraseCredentials()
    {
        $this->plainPassword = null;
    }

    public function getRoles()
    {
        $roles_name = [];
        foreach ($this->roles as $item){
            $roles_name[] = $item->getRoleName();
        }

        return $roles_name;
    }

    public function addRoles(Roles $role)
    {
        $role->addUserGroup($this);
        $this->roles[] = $role;
    }

    public function getRolesList()
    {
        $roles = $this->getRoles();
        $arr = [];
        $rolesToText = $this->rolesToText();
        foreach ($roles as $item){
            $arr[] =  $rolesToText[$item];
        }

        return implode(', ', $arr);
    }

    private function rolesToText(){
        return [
            self::ROLE_ADMINISTRATOR => 'Администратор',
            self::ROLE_USER => 'Пользователь'
        ];
    }
}

src/Testjob/TestjobBundle/Controller/UsersController.php
<?php

namespace Testjob\TestjobBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;

class UsersController extends Controller
{
    /**
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();
        $users = $em->getRepository('TestjobBundle:User')->findAll();

        return $this->render('TestjobBundle:Users:index.html.twig', ['users' => $users]);
    }

    /**
     * @param $id
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function editAction($id)
    {
        $em = $this->getDoctrine()->getManager();
        $user = $em->getRepository('TestjobBundle:User')->find($id);

        if (!$user) {
            throw $this->createNotFoundException('Такого пользователя не существует');
        }

        return $this->render('TestjobBundle:Users:edit.html.twig', ['user' => $user]);
    }

    /**
     * @param $id
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function deleteAction($id)
    {
        $em = $this->getDoctrine()->getManager();
        $user = $em->getRepository('TestjobBundle:User')->find($id);

        if (!$user) {
            throw $this->createNotFoundException('Такого пользователя не существует');
        }

        $em->remove($user);
        $em->flush();

        return $this->redirect(
            $this->generateUrl("testjob_users")
        );
    }

    /**
     * @param $id
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     * @throws \Exception
     */
    public function confirmAction($id)
    {
        $em = $this->getDoctrine()->getManager();
        $user = $em->getRepository('TestjobBundle:User')->find($id);

        if (!$user) {
            throw $this->createNotFoundException('Такого пользователя не существует');
        }

        $user->setConfirmed(true);
        $user->setRegistred(new \DateTime());
        $em->flush();

        //послать почту
        $message = \Swift_Message::newInstance()
            ->setSubject('Подтверждение регистрации на testjob')
            ->setFrom('testjob1717@gmail.com')
            ->setTo($user->getEmail())
            ->setBody($this->renderView('TestjobBundle:Security:confirm_mail.html.twig', ['name' => $user->getUsername()]));

        $this->get('mailer')->send($message);

        return $this->redirect(
            $this->generateUrl("testjob_users")
        );
    }

    /**
     * @param $id
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function banAction($id)
    {
        $em = $this->getDoctrine()->getManager();
        $user = $em->getRepository('TestjobBundle:User')->find($id);

        if (!$user) {
            throw $this->createNotFoundException('Такого пользователя не существует');
        }

        if($user->getBanned()){
            $user->setBanned(false);
        }else{
            $user->setBanned(true);
        }

        $em->flush();

        return $this->redirect(
            $this->generateUrl("testjob_users")
        );
    }
}

src/Testjob/TestjobBundle/Resources/views/Users/edit.html.twig
{% extends '::base.html.twig' %}

{% block page_title %}{% endblock %}

{% block page_content %}

    <div class="col-md-12">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Inbox</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body no-padding">

                <div class="table-responsive mailbox-messages">
                    <table class="table table-hover table-striped">
                        <tbody>
                        <tr>
                            <td class="mailbox-name">ID: </td>
                            <td class="mailbox-subject">{{ user.id }}</td>
                        </tr>
                        <tr>
                            <td class="mailbox-name">ФИО: </td>
                            <td class="mailbox-subject">{{ user.fio }}</td>
                        </tr>
                        <tr>
                            <td class="mailbox-name">Логин: </td>
                            <td class="mailbox-subject">{{ user.login }}</td>
                        </tr>
                        <tr>
                            <td class="mailbox-name">День рождения: </td>
                            <td class="mailbox-subject">{{ user.birthday|date('d-m-Y') }}</td>
                        </tr>
                        <tr>
                            <td class="mailbox-name">Роль: </td>
                            <td class="mailbox-subject">{{ user.rolesList }}</td>
                        </tr>
                        <tr>
                            <td class="mailbox-name">Дата регистрации: </td>
                            <td class="mailbox-subject">
                                {% if user.confirmed %}
                                    {{ user.registred|date('d-m-Y') }}
                                {% endif %}
                            </td>
                        </tr>
                        <tr>
                            <td class="mailbox-name">Регистрация: </td>
                            <td class="mailbox-subject">
                                {% if user.banned %}
                                    <span class="label label-danger">Бан</span>
                                {% elseif user.confirmed %}
                                    <span class="label label-success">Одобрено</span>
                                {% else %}
                                    <span class="label label-warning">Ожидает</span>
                                {% endif %}
                            </td>
                        </tr>

                        </tbody>
                    </table>
                    <!-- /.table -->
                </div>
                <!-- /.mail-box-messages -->
            </div>
            <!-- /.box-body -->
            <div class="box-footer no-padding">
                <div class="mailbox-controls">

                    <div class="pull-right">
                        <div class="btn-group">

                            {% if not user.confirmed %}
                                <a href="{{ path('testjob_confirm_user', { 'id': user.id }) }}" class="btn btn-success btn-sm">
                                    Зарегестрировать
                                </a>
                            {% endif %}
                            {% if user.banned %}
                                <a href="{{ path('testjob_ban_user', { 'id': user.id }) }}" class="btn btn-warning btn-sm">
                                    Разблокировать
                                </a>
                            {% else %}
                                <a href="{{ path('testjob_ban_user', { 'id': user.id }) }}" class="btn btn-warning btn-sm">
                                    Заблокировать
                                </a>
                            {% endif %}
                            <a href="{{ path('testjob_delete_user', { 'id': user.id }) }}" class="btn btn-danger btn-sm">
                                Удалить
                            </a>


                        </div>
                        <!-- /.btn-group -->
                    </div>
                    <!-- /.pull-right -->
                </div>
            </div>
        </div>
        <!-- /. box -->
    </div>




{% endblock %}

src/Testjob/TestjobBundle/Resources/views/Users/index.html.twig
{% extends '::base.html.twig' %}

{% block page_title %}{% endblock %}

{% block page_content %}

    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Пользователи</h3>


                </div>
                <!-- /.box-header -->
                <div class="box-body table-responsive no-padding">
                    <table class="table table-hover">
                        <tbody><tr>
                            <th>ID</th>
                            <th>ФИО</th>
                            <th>Логин</th>
                            <th>Роль</th>
                            <th>Дата регистрации</th>
                            <th>Регистрация</th>
                            <th></th>
                        </tr>
                        {% for user in users %}
                        <tr>
                            <td>{{ user.id }}</td>
                            <td>{{ user.fio }}</td>
                            <td>{{ user.login }}</td>
                            <td>{{ user.rolesList }}</td>
                            <td>
                                {% if user.confirmed %}
                                    {{ user.registred|date('d-m-Y') }}
                                {% endif %}
                            </td>
                            <td>
                                {% if user.banned %}
                                    <span class="label label-danger">Бан</span>
                                {% elseif user.confirmed %}
                                    <span class="label label-success">Одобрено</span>
                                {% else %}
                                    <span class="label label-warning">Ожидает</span>
                                {% endif %}
                            </td>
                            <td>
                                <a href="{{ path('testjob_user_edit', { 'id': user.id }) }}"><i class="fa fa-fw fa-edit"></i></a>
                            </td>
                        </tr>
                        {% else %}
                        {% endfor %}

                        </tbody></table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
    </div>
{% endblock %}